name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Check formatting
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          echo "Please run 'gofmt -w .' to fix formatting issues."
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go mod tidy check
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go mod tidy made changes. Please run 'go mod tidy' and commit the changes."
          git diff
          exit 1
        fi
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build CLI
      run: go build -o shuku ./cmd/shuku
    
    - name: Test CLI functionality
      run: |
        ./shuku help || true
        ./shuku compress --help

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Check formatting
      shell: bash
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          echo "Please run 'gofmt -w .' to fix formatting issues."
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go mod tidy check
      shell: bash
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go mod tidy made changes. Please run 'go mod tidy' and commit the changes."
          git diff
          exit 1
        fi
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build CLI
      run: go build -o shuku.exe ./cmd/shuku
    
    - name: Test CLI functionality
      shell: bash
      run: |
        ./shuku.exe help || true
        ./shuku.exe compress --help