name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Check formatting
      run: make check-fmt
    
    - name: Run go vet
      run: make vet
    
    - name: Run go mod tidy check
      run: make check-tidy
    
    - name: Run tests
      run: make test
    
    - name: Build CLI
      run: make build
    
    - name: Test CLI functionality
      run: make test-cli

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Check formatting
      shell: bash
      run: make check-fmt
    
    - name: Run go vet
      run: make vet
    
    - name: Run go mod tidy check
      shell: bash
      run: make check-tidy
    
    - name: Run tests
      run: make test
    
    - name: Build CLI
      run: make build
    
    - name: Test CLI functionality
      shell: bash
      run: make test-cli
