name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Install WebP dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # CGO対応のためのクロスコンパイル環境変数
        CC: gcc
        CXX: g++
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: release-artifacts
        path: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt